// examples/web-vue/demo/Button.vue
<script setup lang="ts">
// A host-owned Vue component. The plugin never imports it — it asks for a
// semantic "Button" via `hostSlot`, and this app decides what it looks like.
import { computed } from "vue";
import type { OnAction } from "unode-vue";

const props = defineProps<{
  children?: unknown;
  intent?: unknown;
  action?: unknown;
  disabled?: unknown;
  dispatch: OnAction;
}>();

const intent = computed(() => {
  const value = props.intent;
  return value === "primary" || value === "secondary" || value === "ghost" || value === "danger"
    ? value
    : "secondary";
});
const isDisabled = computed(() => props.disabled === true);

function onClick() {
  if (!isDisabled.value && props.action) props.dispatch(props.action as { t: string });
}
</script>

<template>
  <button
    :class="`ds-button ds-button--${intent}`"
    :disabled="isDisabled"
    :data-intent="intent"
    @click="onClick"
  >
    {{ String(props.children ?? "") }}
  </button>
</template>

// examples/web-react/demo/Button.tsx
import type { HostComponentProps } from "unode-react";

type ButtonIntent = "primary" | "secondary" | "ghost" | "danger";

function normalizeIntent(intent: unknown): ButtonIntent {
  return intent === "primary" ||
    intent === "secondary" ||
    intent === "ghost" ||
    intent === "danger"
    ? intent
    : "secondary";
}

// A host-owned React component. The plugin never imports it. It only asks for a
// semantic "Button" via `hostSlot`, and this app decides what that looks like.
export function Button({
  children,
  intent,
  dispatch,
  action,
  disabled,
}: HostComponentProps) {
  const buttonIntent = normalizeIntent(intent);
  const isDisabled = disabled === true;

  return (
    <button
      className={`ds-button ds-button--${buttonIntent}`}
      disabled={isDisabled}
      data-intent={buttonIntent}
      onClick={() => !isDisabled && action && dispatch(action as { t: string })}
    >
      {String(children ?? "")}
    </button>
  );
}
