// packages/web-svelte/demo/Button.svelte
<script lang="ts">
  import type { OnAction } from "../src";

  // A host-owned Svelte component. The plugin only asks for a semantic "Button"
  // via hostSlot; this app decides how it looks.
  interface Props {
    children?: unknown;
    intent?: unknown;
    action?: { t: string } | undefined;
    dispatch: OnAction;
  }
  let { children, intent, action, dispatch }: Props = $props();
</script>

<button
  class={`ds-button ds-button--${String(intent ?? "secondary")}`}
  onclick={() => action && dispatch(action)}
>
  {String(children ?? "")}
</button>

// examples/web-react/demo/Button.tsx
import type { HostComponentProps } from "unode-react";

// A host-owned React component. The plugin never imports it. It only asks for a
// semantic "Button" via `hostSlot`, and this app decides what that looks like.
export function Button({ children, intent, dispatch, action }: HostComponentProps) {
  return (
    <button
      className={`ds-button ds-button--${String(intent ?? "secondary")}`}
      onClick={() => action && dispatch(action as { t: string })}
    >
      {String(children ?? "")}
    </button>
  );
}
