// examples/web-svelte/demo/Button.svelte
<script lang="ts">
  import type { OnAction } from "unode-svelte";

  // A host-owned Svelte component. The plugin only asks for a semantic "Button"
  // via hostSlot; this app decides how it looks.
  type ButtonIntent = "primary" | "secondary" | "ghost" | "danger";

  interface Props {
    children?: unknown;
    intent?: unknown;
    action?: { t: string } | undefined;
    disabled?: unknown;
    dispatch: OnAction;
  }

  let { children, intent, action, disabled, dispatch }: Props = $props();

  function normalizeIntent(value: unknown): ButtonIntent {
    return value === "primary" ||
      value === "secondary" ||
      value === "ghost" ||
      value === "danger"
      ? value
      : "secondary";
  }

  const buttonIntent = $derived(normalizeIntent(intent));
  const isDisabled = $derived(disabled === true);
</script>

<button
  class={`ds-button ds-button--${buttonIntent}`}
  data-intent={buttonIntent}
  disabled={isDisabled}
  onclick={() => !isDisabled && action && dispatch(action)}
>
  {String(children ?? "")}
</button>

// examples/web-react/demo/Button.tsx
import type { HostComponentProps } from "unode-react";

type ButtonIntent = "primary" | "secondary" | "ghost" | "danger";

function normalizeIntent(intent: unknown): ButtonIntent {
  return intent === "primary" ||
    intent === "secondary" ||
    intent === "ghost" ||
    intent === "danger"
    ? intent
    : "secondary";
}

// A host-owned React component. The plugin never imports it. It only asks for a
// semantic "Button" via `hostSlot`, and this app decides what that looks like.
export function Button({
  children,
  intent,
  dispatch,
  action,
  disabled,
}: HostComponentProps) {
  const buttonIntent = normalizeIntent(intent);
  const isDisabled = disabled === true;

  return (
    <button
      className={`ds-button ds-button--${buttonIntent}`}
      disabled={isDisabled}
      data-intent={buttonIntent}
      onClick={() => !isDisabled && action && dispatch(action as { t: string })}
    >
      {String(children ?? "")}
    </button>
  );
}
