// packages/unode-solid/src/renderer.ts
// Solid adapter: host-component portal for the universal Unode renderer.
//
// The renderer itself lives in `unode-web-renderer` and produces DOM. Solid
// only fulfills `hostSlot(name)` holes: each mounted slot is a `render` root
// whose props live in a Solid store, so slot updates patch the component
// fine-grained instead of remounting it.

import type { Component } from "solid-js";
import { createComponent, render } from "solid-js/web";
import { createStore, reconcile } from "solid-js/store";
import type { HostPortalAdapter, HostSlotHandle, HostSlotRequest, OnAction } from "unode-web-renderer";

export type { OnAction };

/** Maps a `hostSlot(name)` to the host's Solid component. */
export type HostComponents = Record<string, Component<HostComponentProps>>;

/** Props a host component receives: the plugin's props plus a `dispatch`. */
export type HostComponentProps = Record<string, unknown> & { dispatch: OnAction };

export class SolidPortalAdapter implements HostPortalAdapter {
  constructor(public components: HostComponents) {}

  mount(container: Element, request: HostSlotRequest): HostSlotHandle {
    const component = this.components[request.name];
    if (!component) {
      return { update: () => {}, unmount: () => {} };
    }

    const [props, setProps] = createStore<HostComponentProps>({
      ...request.props,
      dispatch: request.dispatch,
    });
    const dispose = render(() => createComponent(component, props), container);

    return {
      update: (next) =>
        setProps(reconcile({ ...next, dispatch: request.dispatch } as HostComponentProps)),
      unmount: dispose,
    };
  }
}

// packages/unode-react/src/renderer.tsx
// React adapter: a thin mount target for the universal Unode renderer.
//
// The renderer itself (recipes, reactivity, patching) lives in `unode-web-renderer`
// and produces DOM. React's only jobs here are (1) hosting that DOM in a ref and
// (2) fulfilling `hostSlot(name)` holes with the host app's own React components
// through React portals. There is no React-specific renderer to maintain.

import {
  type ComponentType,
} from "react";

import {
  type HostPortalAdapter,
  type HostSlotHandle,
  type HostSlotRequest,
  type OnAction,

} from "unode-web-renderer";

export type { OnAction };

/** Maps a `hostSlot(name)` to the host's React component. */
export type HostComponents = Record<string, ComponentType<HostComponentProps>>;

/** Props a host component receives: the plugin's props plus a `dispatch`. */
export type HostComponentProps = Record<string, unknown> & { dispatch: OnAction };

interface PortalEntry {
  id: number;
  container: Element;
  name: string;
  props: Record<string, unknown>;
  dispatch: OnAction;
}

export class ReactPortalAdapter implements HostPortalAdapter {
  readonly entries = new Map<number, PortalEntry>();
  private seq = 0;
  private readonly listeners = new Set<() => void>();

  constructor(public components: HostComponents) {}

  subscribe(listener: () => void): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  private emit(): void {
    this.listeners.forEach((listener) => listener());
  }

  mount(container: Element, request: HostSlotRequest): HostSlotHandle {
    const id = this.seq++;
    this.entries.set(id, {
      id,
      container,
      name: request.name,
      props: request.props,
      dispatch: request.dispatch,
    });
    this.emit();
    return {
      update: (props) => {
        const entry = this.entries.get(id);
        if (entry) {
          entry.props = props;
          this.emit();
        }
      },
      unmount: () => {
        this.entries.delete(id);
        this.emit();
      },
    };
  }
}
