// packages/unode-react/src/UnodeScreen.tsx
/* eslint-disable react-hooks/refs --
 * The portal adapter is a deliberate external-store pattern: a lazily
 * ref-initialized registry whose entries are rendered as portals, kept in
 * sync via subscribe + forced re-render. */
import { defineRenderer, OnAction, Renderer, ScreenStore } from "unode-web-renderer";
import { HostComponents } from "./renderer";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { ReactPortalAdapter } from "./renderer";

const defaultRenderer = defineRenderer().build();

export interface UnodeScreenProps {
  store: ScreenStore;
  onAction?: OnAction;
  /** A renderer from `defineRenderer()`. Defaults to the built-in recipes. */
  renderer?: Renderer;
  /** Host components that fulfill `hostSlot(name)` holes. */
  components?: HostComponents;
}

/**
 * Mounts a Unode screen. Pass a `renderer` to customize recipes and
 * `components` to back any `hostSlot` with native React components.
 */
export function UnodeScreen({
  store,
  onAction,
  renderer = defaultRenderer,
  components = {},
}: UnodeScreenProps) {
  const hostRef = useRef<HTMLDivElement | null>(null);
  const [, force] = useState(0);
  const adapterRef = useRef<ReactPortalAdapter | null>(null);
  if (!adapterRef.current) adapterRef.current = new ReactPortalAdapter(components);
  const adapter = adapterRef.current;
  adapter.components = components;

  useEffect(() => adapter.subscribe(() => force((n) => n + 1)), [adapter]);

  useEffect(() => {
    const el = hostRef.current;
    if (!el) return;
    const handle = renderer.mount(el, store, { onAction, portal: adapter });
    return () => handle.unmount();
  }, [store, renderer, onAction, adapter]);

  return (
    <div ref={hostRef} className="unode-root">
      {[...adapter.entries.values()].map((entry) => {
        const Component = adapter.components[entry.name];
        if (!Component) return null;
        return createPortal(
          <Component {...entry.props} dispatch={entry.dispatch} />,
          entry.container,
          String(entry.id),
        );
      })}
    </div>
  );
}

export default UnodeScreen;

// packages/unode-solid/src/UnodeScreen.ts
// The Solid mount target: hosts the DOM produced by the universal renderer
// and wires the host-component portal. Solid components may return real DOM
// nodes, so no JSX is needed here.

import { onCleanup, onMount } from "solid-js";
import {
  type OnAction,
  type Renderer,
  type RendererHandle,
  ScreenStore,
  defineRenderer,
} from "unode-web-renderer";

import { type HostComponents, SolidPortalAdapter } from "./renderer";

const defaultRenderer = defineRenderer().build();

export interface UnodeScreenProps {
  store: ScreenStore;
  onAction?: OnAction;
  /** A renderer from `defineRenderer()`. Defaults to the built-in recipes. */
  renderer?: Renderer;
  /** Host components that fulfill `hostSlot(name)` holes. */
  components?: HostComponents;
}

/**
 * Mounts a Unode screen. Pass a `renderer` to customize recipes and
 * `components` to back any `hostSlot` with native Solid components.
 */
export function UnodeScreen(props: UnodeScreenProps): HTMLElement {
  const host = document.createElement("div");
  host.className = "unode-root";

  let handle: RendererHandle | undefined;
  onMount(() => {
    const adapter = new SolidPortalAdapter(props.components ?? {});
    handle = (props.renderer ?? defaultRenderer).mount(host, props.store, {
      onAction: props.onAction,
      portal: adapter,
    });
  });
  onCleanup(() => handle?.unmount());

  return host;
}
